### ISSUE TITLE
Permissions make no sense

### ISSUE THREAD

**Issue by JScott** [telusdigital/ansible-fluentd#4]
We use fluentd_user and fluentd_group to set permissions when using file and template. However, we don't feed those to upstart so it runs fluentd as root. This effectively means that fluentd_user and fluentd_group don't mean anything to fluentd and don't limit fluentd's access.

We need to figure out if we want to add those to upstart or remove them entirely to enforce root/root, which is what we currently effectively do.

**Comment by noqcks** [comment]
fixed by 63b9b4f7a7429ef6282231535c6210a404fe2735
